### ISSUE TITLE
Mod Director dont works for Internet Archive

### ISSUE THREAD

**Issue by ThunderCrafter2** [Janrupf/mod-director#28]
It would be helpfull if Mod director worked on the Internet Archive page for old downloads that still work despite the page being gone
http://web.archive.org/web/20181020031322/http://10paksmods.net/pmp.html
tried it with the 1.12.2 Versions but it didn´t work
also not with the follow keys

Otherwise all works fine Exscept for curesfore due to the recent change but that is already mentioned in another issue
thank your for the Awesome mod would have no idea what to do without it

```
MultiMC version 0.6.16-3431


Launched instance in online mode

authserver.mojang.com resolves to
    [18.66.119.38, 18.66.119.42, 18.66.119.35, 18.66.119.37]

session.minecraft.net resolves to
    [35.153.153.200, 100.24.172.95, 34.199.236.154]

textures.minecraft.net resolves to
    [18.66.112.103, 18.66.112.79, 18.66.112.77, 18.66.112.60]

api.mojang.com resolves to
    [108.138.17.3, 108.138.17.41, 108.138.17.109, 108.138.17.100]


Minecraft folder is
DMultiMCinstances1.12.22.minecraft


Java path is
CProgram FilesJavajre1.8.0_281binjavaw.exe


Checking Java version...
Java is version 1.8.0_281, using 64-bit architecture, from Oracle Corporation.


Main Class
  net.minecraft.launchwrapper.Launch

Native path
  DMultiMCinstances1.12.22natives

Libraries
  DMultiMClibrariesnetjavajinputjinput2.0.5jinput-2.0.5.jar
  DMultiMClibrariesnetjavajutilsjutils1.0.0jutils-1.0.0.jar
  DMultiMClibrariesorglwjgllwjgllwjgl2.9.4-nightly-20150209lwjgl-2.9.4-nightly-20150209.jar
  DMultiMClibrariesorglwjgllwjgllwjgl_util2.9.4-nightly-20150209lwjgl_util-2.9.4-nightly-20150209.jar
  DMultiMClibrariescommojangpatchy1.3.9patchy-1.3.9.jar
  DMultiMClibrariesoshi-projectoshi-core1.1oshi-core-1.1.jar
  DMultiMClibrariesnetjavadevjnajna4.4.0jna-4.4.0.jar
  DMultiMClibrariesnetjavadevjnaplatform3.4.0platform-3.4.0.jar
  DMultiMClibrariescomibmicuicu4j-core-mojang51.2icu4j-core-mojang-51.2.jar
  DMultiMClibrariesnetsfjopt-simplejopt-simple5.0.3jopt-simple-5.0.3.jar
  DMultiMClibrariescompaulscodecodecjorbis20101023codecjorbis-20101023.jar
  DMultiMClibrariescompaulscodecodecwav20101023codecwav-20101023.jar
  DMultiMClibrariescompaulscodelibraryjavasound20101123libraryjavasound-20101123.jar
  DMultiMClibrariescompaulscodelibrarylwjglopenal20100824librarylwjglopenal-20100824.jar
  DMultiMClibrariescompaulscodesoundsystem20120107soundsystem-20120107.jar
  DMultiMClibrariesionettynetty-all4.1.9.Finalnetty-all-4.1.9.Final.jar
  DMultiMClibrariescomgoogleguavaguava21.0guava-21.0.jar
  DMultiMClibrariesorgapachecommonscommons-lang33.5commons-lang3-3.5.jar
  DMultiMClibrariescommons-iocommons-io2.5commons-io-2.5.jar
  DMultiMClibrariescommons-codeccommons-codec1.10commons-codec-1.10.jar
  DMultiMClibrariescomgooglecodegsongson2.8.0gson-2.8.0.jar
  DMultiMClibrariescommojangauthlib1.5.25authlib-1.5.25.jar
  DMultiMClibrariescommojangrealms1.10.22realms-1.10.22.jar
  DMultiMClibrariesorgapachecommonscommons-compress1.8.1commons-compress-1.8.1.jar
  DMultiMClibrariesorgapachehttpcomponentshttpclient4.3.3httpclient-4.3.3.jar
  DMultiMClibrariescommons-loggingcommons-logging1.1.3commons-logging-1.1.3.jar
  DMultiMClibrariesorgapachehttpcomponentshttpcore4.3.2httpcore-4.3.2.jar
  DMultiMClibrariesitunimidsifastutil7.1.0fastutil-7.1.0.jar
  DMultiMClibrariesorgapachelogginglog4jlog4j-api2.16.0log4j-api-2.16.0.jar
  DMultiMClibrariesorgapachelogginglog4jlog4j-core2.16.0log4j-core-2.16.0.jar
  DMultiMClibrariescommojangtext2speech1.10.3text2speech-1.10.3.jar
  DMultiMClibrariesnetminecraftforgeforge1.12.2-14.23.5.2860forge-1.12.2-14.23.5.2860-universal.jar
  DMultiMClibrariesorgow2asmasm-debug-all5.2asm-debug-all-5.2.jar
  DMultiMClibrariesnetminecraftlaunchwrapper1.12launchwrapper-1.12.jar
  DMultiMClibrariesorgjlinejline3.5.1jline-3.5.1.jar
  DMultiMClibrariescomtypesafeakkaakka-actor_2.112.3.3akka-actor_2.11-2.3.3.jar
  DMultiMClibrariescomtypesafeconfig1.2.1config-1.2.1.jar
  DMultiMClibrariesorgscala-langscala-actors-migration_2.111.1.0scala-actors-migration_2.11-1.1.0.jar
  DMultiMClibrariesorgscala-langscala-compiler2.11.1scala-compiler-2.11.1.jar
  DMultiMClibrariesorgscala-langpluginsscala-continuations-library_2.111.0.2_mcscala-continuations-library_2.11-1.0.2_mc.jar
  DMultiMClibrariesorgscala-langpluginsscala-continuations-plugin_2.11.11.0.2_mcscala-continuations-plugin_2.11.1-1.0.2_mc.jar
  DMultiMClibrariesorgscala-langscala-library2.11.1scala-library-2.11.1.jar
  DMultiMClibrariesorgscala-langscala-parser-combinators_2.111.0.1scala-parser-combinators_2.11-1.0.1.jar
  DMultiMClibrariesorgscala-langscala-reflect2.11.1scala-reflect-2.11.1.jar
  DMultiMClibrariesorgscala-langscala-swing_2.111.0.1scala-swing_2.11-1.0.1.jar
  DMultiMClibrariesorgscala-langscala-xml_2.111.0.2scala-xml_2.11-1.0.2.jar
  DMultiMClibrarieslzmalzma0.0.1lzma-0.0.1.jar
  DMultiMClibrariesjava3dvecmath1.5.2vecmath-1.5.2.jar
  DMultiMClibrariesnetsftrove4jtrove4j3.0.3trove4j-3.0.3.jar
  DMultiMClibrariesorgapachemavenmaven-artifact3.5.3maven-artifact-3.5.3.jar
  DMultiMClibrariescommojangminecraft1.12.2minecraft-1.12.2-client.jar

Native libraries
  DMultiMClibrariesnetjavajinputjinput-platform2.0.5jinput-platform-2.0.5-natives-windows.jar
  DMultiMClibrariesorglwjgllwjgllwjgl-platform2.9.4-nightly-20150209lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  DMultiMClibrariescommojangtext2speech1.10.3text2speech-1.10.3-natives-windows.jar

Mods
  [❌] athenaeum-1.12.2-1.19.5.jar (disabled)
  [❌] BlockDropsTweaker-1.12.2-2.4.jar (disabled)
  [❌] CraftTweaker2-1.12-4.1.20.678.jar (disabled)
  [❌] DynamicLights-1.12.2.jar (disabled)
  [✔️] EnchantingTable-1.12-1.1.3
  [❌] Fish's+Undead+Rising-1.3.1.jar (disabled)
  [❌] lycanitesmobs-1.12.2-2.0.8.5.jar (disabled)
  [📁] memory_repo (folder)
  [✔️] mod-director-launchwrapper-1.5.1-SNAPSHOT-all
  [❌] onslaught-1.12.2-1.3.2.jar (disabled)
  [✔️] OptiFine_1.12.2_HD_U_G5
  [❌] PrimalCore-1.12.2-0.6.105.jar (disabled)
  [❌] RealisticTorches-1.12.2-2.1.2.jar (disabled)
  [❌] TheBetweenlands-3.8.1-universal.jar (disabled)

Params
  --username  --version 1.12.2 --gameDir DMultiMCinstances1.12.22.minecraft --assetsDir DMultiMCassets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size max (if available)

Java Arguments
[-d64, -XX+AggressiveOpts, -XXHeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx3814m, -Duser.language=en]


Minecraft process ID 13936


Using onesix launcher.

[220209] [mainINFO] [LaunchWrapper] Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[220209] [mainINFO] [LaunchWrapper] Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[220209] [mainINFO] [LaunchWrapper] Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[220209] [mainINFO] [FML] Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[220209] [mainINFO] [FML] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 10amd6410.0, installed at CProgram FilesJavajre1.8.0_281
[220209] [mainINFO] [FML] Searching DMultiMCinstances1.12.22.minecraftmods for mods
[220209] [mainINFO] [FML] Loading tweaker net.jan.moddirector.launchwrapper.ModDirectorTweaker from mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar
[220209] [mainINFO] [FML] Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5.jar
[220209] [mainINFO] [LaunchWrapper] Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[220209] [mainINFO] [LaunchWrapper] Loading tweak class name net.jan.moddirector.launchwrapper.ModDirectorTweaker
[220209] [mainINFO] [ModDirector[CORE]] Mod director loaded!
[220209] [mainINFO] [ModDirectorTweaker[Launchwrapper]] ModDirector bootstrapped from Launchwrapper!
[220209] [mainINFO] [LaunchWrapper] Loading tweak class name optifine.OptiFineForgeTweaker
[220209] [mainINFO] [LaunchWrapper] Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[220209] [mainINFO] [LaunchWrapper] Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[220209] [mainINFO] [LaunchWrapper] Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[220209] [mainINFO] [LaunchWrapper] Calling tweak class net.jan.moddirector.launchwrapper.ModDirectorTweaker
[220209] [mainINFO] [ModDirectorConfigurationController[CORE]] Loading config configmod-directorLapis.url.json
[220209] [mainINFO] [ModDirectorConfigurationController[CORE]] Loading config configmod-directorOptifine.url.json
[220209] [mainINFO] [ModDirectorConfigurationController[CORE]] Loading config configmod-directorpmp.url.json
[220210] [mainERROR] [ModDirector[CORE]] An exception occurred while performing asynchronous work
java.util.concurrent.ExecutionException java.nio.file.InvalidPathException Illegal char  at index 24 web20181020031322http10paksmods.netpmp.html
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[1.8.0_281]
	at net.jan.moddirector.core.ModDirector.awaitAll(ModDirector.java212) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java120) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java47) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java115) [launchwrapper-1.12.jar]
	at net.minecraft.launchwrapper.Launch.main(Launch.java28) [launchwrapper-1.12.jar]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java210) [NewLaunch.jar]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java245) [NewLaunch.jar]
	at org.multimc.EntryPoint.listen(EntryPoint.java143) [NewLaunch.jar]
	at org.multimc.EntryPoint.main(EntryPoint.java34) [NewLaunch.jar]
Caused by java.nio.file.InvalidPathException Illegal char  at index 24 web20181020031322http10paksmods.netpmp.html
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[1.8.0_281]
	at java.nio.file.Paths.get(Unknown Source) ~[1.8.0_281]
	at net.jan.moddirector.core.configuration.type.UrlRemoteMod.queryInformation(UrlRemoteMod.java133) ~[UrlRemoteMod.class1.5.1-SNAPSHOT]
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java68) ~[InstallController.class1.5.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[1.8.0_281]
	at java.lang.Thread.run(Unknown Source) ~[1.8.0_281]
[220210] [mainERROR] [ModDirector[CORE]] ============================================================
[220210] [mainERROR] [ModDirector[CORE]] Summary of 1 encountered errors
[220210] [mainERROR] [ModDirector[CORE]] An exception occurred while performing asynchronous work
java.util.concurrent.ExecutionException java.nio.file.InvalidPathException Illegal char  at index 24 web20181020031322http10paksmods.netpmp.html
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[1.8.0_281]
	at net.jan.moddirector.core.ModDirector.awaitAll(ModDirector.java212) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java120) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java47) [mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java115) [launchwrapper-1.12.jar]
	at net.minecraft.launchwrapper.Launch.main(Launch.java28) [launchwrapper-1.12.jar]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java210) [NewLaunch.jar]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java245) [NewLaunch.jar]
	at org.multimc.EntryPoint.listen(EntryPoint.java143) [NewLaunch.jar]
	at org.multimc.EntryPoint.main(EntryPoint.java34) [NewLaunch.jar]
Caused by java.nio.file.InvalidPathException Illegal char  at index 24 web20181020031322http10paksmods.netpmp.html
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[1.8.0_281]
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[1.8.0_281]
	at java.nio.file.Paths.get(Unknown Source) ~[1.8.0_281]
	at net.jan.moddirector.core.configuration.type.UrlRemoteMod.queryInformation(UrlRemoteMod.java133) ~[UrlRemoteMod.class1.5.1-SNAPSHOT]
	at net.jan.moddirector.core.manage.InstallController.lambda$createPreInstallTasks$0(InstallController.java68) ~[InstallController.class1.5.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[1.8.0_281]
	at java.lang.Thread.run(Unknown Source) ~[1.8.0_281]
[220210] [mainERROR] [ModDirector[CORE]] ============================================================
[220210] [mainERROR] [LaunchWrapper] Unable to launch
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException null
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java49) ~[forge-1.12.2-14.23.5.2860-universal.jar]
	at java.lang.SecurityManager.checkExit(Unknown Source) ~[1.8.0_281]
	at java.lang.Runtime.exit(Unknown Source) ~[1.8.0_281]
	at java.lang.System.exit(Unknown Source) ~[1.8.0_281]
	at net.jan.moddirector.core.ModDirector.errorExit(ModDirector.java206) ~[mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.core.ModDirector.activate(ModDirector.java124) ~[mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.jan.moddirector.launchwrapper.ModDirectorTweaker.injectIntoClassLoader(ModDirectorTweaker.java47) ~[mod-director-launchwrapper-1.5.1-SNAPSHOT-all.jar1.5.1-SNAPSHOT]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java115) [launchwrapper-1.12.jar]
	at net.minecraft.launchwrapper.Launch.main(Launch.java28) [launchwrapper-1.12.jar]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java210) [NewLaunch.jar]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java245) [NewLaunch.jar]
	at org.multimc.EntryPoint.listen(EntryPoint.java143) [NewLaunch.jar]
	at org.multimc.EntryPoint.main(EntryPoint.java34) [NewLaunch.jar]
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass213] Failed to start Minecraft
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] java.lang.reflect.InvocationTargetException
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at java.lang.reflect.Method.invoke(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java210)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java245)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at org.multimc.EntryPoint.listen(EntryPoint.java143)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunch245] 	at org.multimc.EntryPoint.main(EntryPoint.java34)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] Caused by net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java49)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at java.lang.SecurityManager.checkExit(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at java.lang.Runtime.exit(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at java.lang.System.exit(Unknown Source)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java138)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	at net.minecraft.launchwrapper.Launch.main(Launch.java28)
[220210] [mainINFO] [STDERR] [org.multimc.onesix.OneSixLauncherlaunchWithMainClass214] 	... 8 more
[220210] [mainINFO] [STDOUT] [org.multimc.EntryPointmain37] Exiting with -1
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java49)
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] 	at java.lang.SecurityManager.checkExit(Unknown Source)
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] 	at java.lang.Runtime.exit(Unknown Source)
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] 	at java.lang.System.exit(Unknown Source)
[220210] [mainINFO] [STDERR] [java.lang.ThreadGroupuncaughtException-1] 	at org.multimc.EntryPoint.main(EntryPoint.java38)



```

**Comment by Lylythii** [comment]
Try this:
```
{
    "url": "http://web.archive.org/web/20190127003542/http://10paksmods.net/downloads/pmp-1.12.1.jar",
    "follows": ["pmp-1.12.1"],
    "fileName": "pmp-1.12.1.jar"
}
```
I named the file `pmp.url.json` just to clarify, worked perfectly fine for me.
However it appears PlantMegaPack doesn't actually launch. The file gets installed but that's all. I might look into figuring that issue out as the mod may be of use to myself too. I'll keep you updated!

Update: By the looks of things the `.jar` file that Mod Director installs is corrupted & is why the mod does not launch for me, though a regular install doesn't have this issue. Unsure why.

Note: There is a morally questionable alternative solution if it suits you; Considering the mod `.jar` file that is archived on Archive.org isn't by any means rewarding the author via downloads, *technically speaking* it would be no different if you chose to host the file elsewhere.
Inside a GitHub repository may work for you.
